url: https://couverture.github.io
baseurl: 
app_signin_dev: http://localhost:6543/sign-in
app_signin_prod: https://app.couverture.io/sign-in

# Site settings
title: Couverture (beta)
email: support@couverture.io
description: "Couverture is a differential code coverage service that publishes coverage reports to your pull requests and highlights the parts of your source code that need testing."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Alex Conrad
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/couvertureio
  - title: github
    url: https://github.com/couverture
  - title: envelope
    url: mailto:support@couverture.io

# Postal address (add as many lines as necessary)
address:
  - line: San Francisco, CA

# Build settings
markdown: kramdown
permalink: pretty
